/**
 * Procedural memory — Orchestre learns from rejections.
 *
 * Every Wave 4 audit (or explicit user rejection) records a 'rejection' event in
 * events.jsonl with {pattern, context, reason}. When the same pattern has been
 * rejected >= threshold times (default 3), it becomes a LEARNED PATTERN and is
 * persisted to core/memory/learned-patterns.md for future waves to read.
 *
 * Wave 2 and Wave 3 agents reference that file at their start, so Orchestre
 * progressively avoids repeating rejected patterns without any extra UX.
 *
 * API:
 *   recordRejection(root, {pattern, context, reason, wave, source})
 *   getLearnedPatterns(root, {threshold=3})      → [{pattern, count, contexts, reasons, first, last}]
 *   renderLearnedMarkdown(root, {threshold=3})   → full file content (string)
 *   updateLearnedPatternsFile(repoRoot, root, {threshold=3, filePath?}) → {path, updated, count}
 */
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { append, read } from './state-store.mjs';

export const DEFAULT_THRESHOLD = 3;

export function recordRejection(projectRoot, { pattern, context, reason, wave, source = 'wave-4-auditor' } = {}) {
  if (!pattern || typeof pattern !== 'string') throw new TypeError('recordRejection: pattern is required');
  return append(projectRoot, {
    type: 'rejection',
    wave: typeof wave === 'number' ? wave : null,
    data: {
      pattern: pattern.trim(),
      context: (context || '').trim() || null,
      reason: (reason || '').trim() || null,
      source,
    },
  });
}

export function getLearnedPatterns(projectRoot, { threshold = DEFAULT_THRESHOLD } = {}) {
  const events = read(projectRoot, { type: 'rejection' });
  const byPattern = new Map();

  for (const e of events) {
    const p = e.data?.pattern;
    if (!p) continue;
    const agg = byPattern.get(p) || {
      pattern: p,
      count: 0,
      contexts: new Set(),
      reasons: new Set(),
      first: e.ts,
      last: e.ts,
    };
    agg.count += 1;
    if (e.data.context) agg.contexts.add(e.data.context);
    if (e.data.reason) agg.reasons.add(e.data.reason);
    if (!agg.first || e.ts < agg.first) agg.first = e.ts;
    if (!agg.last || e.ts > agg.last) agg.last = e.ts;
    byPattern.set(p, agg);
  }

  return [...byPattern.values()]
    .filter(agg => agg.count >= threshold)
    .map(agg => ({
      pattern: agg.pattern,
      count: agg.count,
      contexts: [...agg.contexts],
      reasons: [...agg.reasons],
      first: agg.first,
      last: agg.last,
    }))
    .sort((a, b) => b.count - a.count);
}

export function renderLearnedMarkdown(projectRoot, { threshold = DEFAULT_THRESHOLD } = {}) {
  const learned = getLearnedPatterns(projectRoot, { threshold });
  const header = [
    '# Learned Patterns',
    '',
    '> Auto-generated by Orchestre. Patterns rejected ≥ ' + threshold + ' times.',
    '> Future waves read this file and avoid these patterns.',
    '> DO NOT edit manually — re-generated by `updateLearnedPatternsFile()`.',
    '',
  ].join('\n');

  if (learned.length === 0) {
    return header + '_No learned patterns yet._\n';
  }

  const sections = learned.map((p, i) => {
    const ctx = p.contexts.length ? `\n**Contexts:** ${p.contexts.map(c => `\`${c}\``).join(', ')}` : '';
    const reasons = p.reasons.length ? '\n**Reasons:**\n' + p.reasons.map(r => `- ${r}`).join('\n') : '';
    return [
      `## ${i + 1}. ${p.pattern}`,
      '',
      `Rejected **${p.count}** time${p.count === 1 ? '' : 's'} (first ${p.first}, last ${p.last}).${ctx}${reasons}`,
    ].join('\n');
  });

  return header + sections.join('\n\n') + '\n';
}

export function updateLearnedPatternsFile(repoRoot, projectRoot, { threshold = DEFAULT_THRESHOLD, filePath } = {}) {
  const target = filePath
    ? resolve(filePath)
    : resolve(repoRoot, 'core', 'memory', 'learned-patterns.md');

  const content = renderLearnedMarkdown(projectRoot, { threshold });
  const prev = existsSync(target) ? readFileSync(target, 'utf8') : null;

  if (prev === content) {
    return { path: target, updated: false, count: getLearnedPatterns(projectRoot, { threshold }).length };
  }

  mkdirSync(dirname(target), { recursive: true });
  const tmp = target + '.tmp';
  writeFileSync(tmp, content);
  renameSync(tmp, target);
  return { path: target, updated: true, count: getLearnedPatterns(projectRoot, { threshold }).length };
}
