/**
 * Database types — generated by supabase gen types.
 * Minimal version for showcase purposes.
 */

export type Database = {
  public: {
    Tables: {
      invoices: {
        Row: {
          id: string
          user_id: string
          client_name: string
          client_email: string
          status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled'
          amount_cents: number
          currency: string
          due_date: string
          items: InvoiceItem[]
          stripe_payment_link: string | null
          paid_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['invoices']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['invoices']['Insert']>
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          business_name: string | null
          stripe_customer_id: string | null
          plan: 'free' | 'pro'
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
    }
  }
}

type InvoiceItem = {
  description: string
  quantity: number
  unit_price_cents: number
}
